services:
  - type: web
    name: ecommerce-website
    env: node
    buildCommand: cd server && chmod +x build.sh && ./build.sh
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production 